### PR TITLE
Hotfix/23.09 hotfix3 Fix address/entity Tx ordering

### PR DESCRIPTION
**Pull request by myrho**

### CODE REVIEW

**Comment by soad003** [comment]
I have reviewed the changes. Looks good to me but its hard to test with complex cases with many transactions. I tried to add some more (edge) cases to the test suite. 

Changes:

- Added testcases to reassure that result is the same regardless of pagesize
- Added data to test merging of in and out txs
- Simplified the tx merging logic
- Fixed linter warnings
- Fixed that pagesize was not respected if a direction was given

@myrho  please have another look at the changes, esp. the merging logic. It might be worthwile to add some comments to explain and comment the code since its rather complex.

**Review by soad003 — APPROVED** [review]

**Comment by myrho** [comment]
Still there are issues for eth and tokens. I'm on it.

**Review by soad003 — APPROVED** [review]
I have tried to clean up the fix a bit and make it a the code a bit easier to follow. I hope this rather complex piece of code is easier to debug now for potential future bugs and extensions.

**Comment by myrho** [comment]
Pretty nice cleanup! I just think we should consistently name the currency/network parameter  either `currency` or `network`. Now we have both which might be confusing.

**Comment by soad003** [comment]
@myrho I agree, i think over time we should switch to the name network, but its true that it might be confusing.

**Comment by myrho** [comment]
Would you like to align the naming for now?

**Comment by soad003** [comment]
no lets rename the parameter network to currency and to the alignment outside of the context of this hotfix

**Pull request merged**
